#!/bin/sh


export ERL_LIBS="../../deps:../../_build/default/lib"
export ERL_FLAGS="-pz ../../ebin -pz ebin -pz _build/default/lib/piqi_rpc_process_info/ebin"


erl -s piqi_rpc start \
<<!
piqi_rpc:start().
piqi_rpc:add_service({process_info_example, process_info_piqi, "process-info"}).
io:format("~s~n", [os:cmd("./client.sh")]).
timer:sleep(1000).  % wait for output flush
erlang:halt().
!

