#!/bin/sh


PA="-pa ebin"
export ERL_LIBS="deps"


erl $PA -s piqi_rpc start \
<<!
piqi_rpc:start().
piqi_rpc:add_service({process_info_example, process_info_piqi, "process-info"}).
io:format("~s~n", [os:cmd("./client.sh")]).
timer:sleep(1000).  % wait for output flush
erlang:halt().
!

